
export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING_FAIL = "USER_LOADING_FAIL";

export const CREATE_BLOG = "CREATE_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const GET_BLOGS = "GET_BLOGS";
export const GET_ALL_BLOGS = "GET_ALL_BLOGS";

export const CREATE_ARTS = "CREATE_ARTS";
export const DELETE_ARTS = "DELETE_ARTS";
export const UPDATE_ARTS = "UPDATE_ARTS";
export const GET_ARTS = "GET_ARTS";
export const GET_ARTS_DETAIL = "GET_ARTS_DETAIL";
export const GET_ALL_ARTS = "GET_ALL_ARTS";

export const CREATE_ECONOMICS = "CREATE_ECONOMICS";
export const DELETE_ECONOMICS = "DELETE_ECONOMICS";
export const UPDATE_ECONOMICS = "UPDATE_ECONOMICS";
export const GET_ECONOMICS = "GET_ECONOMICS";
export const GET_ECO_DETAIL = "GET_ECO_DETAIL";
export const GET_ALL_ECONOMICS = "GET_ALL_ECONOMICS";

export const CREATE_EDUCATION = "CREATE_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const GET_EDUCATION = "GET_EDUCATION";
export const GET_ALL_EDUCATION = "GET_ALL_EDUCATION";

export const CREATE_LITERATURE = "CREATE_LITERATURE";
export const DELETE_LITERATURE = "DELETE_LITERATURE";
export const UPDATE_LITERATURE = "UPDATE_LITERATURE";
export const GET_LITERATURE = "GET_LITERATURE";
export const GET_ALL_LITERATURE = "GET_ALL_LITERATURE";

export const CREATE_POLITICS = "CREATE_POLITICS";
export const DELETE_POLITICS = "DELETE_POLITICS";
export const UPDATE_POLITICS = "UPDATE_POLITICS";
export const GET_POLITICS = "GET_POLITICS";
export const GET_ALL_POLITICS = "GET_ALL_POLITICS";

export const CREATE_TECHNOLOGY = "CREATE_TECHNOLOGY";
export const DELETE_TECHNOLOGY = "DELETE_TECHNOLOGY";
export const UPDATE_TECHNOLOGY = "UPDATE_TECHNOLOGY";
export const GET_TECHNOLOGY = "GET_TECHNOLOGY";
export const GET_ALL_TECHNOLOGY = "GET_ALL_TECHNOLOGY";

export const CREATE_TOURISM = "CREATE_TOURISM";
export const DELETE_TOURISM = "DELETE_TOURISM";
export const UPDATE_TOURISM = "UPDATE_TOURISM";
export const GET_TOURISM = "GET_TOURISM";
export const GET_ALL_TOURISM = "GET_ALL_TOURISM";